Update backup

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,46 +1,71 @@
 #!/bin/bash
-if [ ! -f /data/odoo/odoo-server.conf ]
+readonly RED="\e[31m"
+readonly YELLOW="\e[33m"
+readonly GREEN="\e[32m"
+readonly STD="\e[0m"
+
+if [ $# -lt 2 ]
   then
-    echo "Error! odoo-server.conf not found!"
-    exit 2
+    echo -e "${RED}Error! Too few arguments supplied!${STD}"
+    echo -e "${STD}Command: jd-backup <customer> <db>"
+    echo -e "${STD}--- or ---"
+    echo -e "${STD}Command: jd-backup -c <configfile>"
+    exit 1
 fi
 
-declare -A conf
+HASERROR=0
 
-IFS="="
-while read -r name value
-do
-  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
-  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
-  conf[$key]=$val
-done < /data/odoo/odoo-server.conf
-
-if [ ! -d /backup ]
-  then
-    mkdir /backup
-fi
-DATE=$(date +"%Y%m%d%H%M")
-
-DBFILE=/backup/${DBNAME}_${DATE}.dump
-TARFILE=/backup/${DBNAME}_${DATE}.tar
-
-PWD=${conf[db_password]}
-export PGPASSWORD=$PWD
-echo "Backup of database..."
-pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} -f ${DBFILE} $DBNAME
-if [ $? -ne 0 ]
-  then
-    echo "Error! DB Backup failed!"
-    exit 2
-fi
-echo "Database saved"
-
-echo "Backup of files..."
-tar -cvf ${TARFILE} /data/odoo
-if [ $? -ne 0 ]
+if [ "$1" = "-c" ]
   then 
-    echo "Error! File backup failed!"
+    declare -A conf
+
+    IFS="="
+    while read -r name value
+      do
+        CUSTOMER=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
+        DB=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
+        conf["$CUSTOMER"]=$DB
+    done < $2
+    for KEY in "${!conf[@]}"
+      do
+        CUSTOMER=$KEY
+        DB=${conf["$KEY"]}
+        echo -e "${YELLOW}Starting backup for database ${DB} of ${CUSTOMER}...${STD}"
+        docker run -ti --volumes-from $CUSTOMER.data -v /jamoshared/backup:/backup --rm --env DBNAME=$DB jamotion/odoo-backup &> /jamoshared/backup/$CUSTOMER.log
+        if [ $? -ne 0 ]
+          then 
+            echo -e "${RED}Backup for ${CUSTOMER} with  ${DB} failed!${STD}"
+            HASERROR=1
+          else
+            echo -e "${GREEN}Backup for ${DB} successful done${STD}"
+        fi
+    done
+    echo -e "{YELLOW}Removing files older than 30 days...${STD}"
+    find /jamoshared/backup/ -type f -mtime +30 -exec rm {} \;  
+    if [ $? -ne 0 ]
+      then
+        echo -e "${RED}Removing old files failed!${STD}"
+        HASERROR=1
+      else
+        echo -e "${GREEN}Old files sucessfully removed${STD}"
+    fi
+  else
+    CUSTOMER=$1
+    DB=$2
+
+    echo -e "${YELLOW}Starting backup for database ${DB} of ${CUSTOMER}...${STD}"
+    docker run -ti --volumes-from $CUSTOMER.data -v /jamoshared/backup:/backup --rm --env DBNAME=$DB jamotion/odoo-backup &> /jamoshared/backup/$CUSTOMER.log
+    if [ $? -ne 0 ]
+      then 
+        echo -e "${RED}Backup for ${CUSTOMER} with  ${DB} failed!${STD}"
+        HASERROR=1
+      else
+        echo -e "${GREEN}Backup for ${DB} successful done${STD}"
+    fi
+fi
+
+if [ "$HASERROR" = "1" ]
+  then 
+    echo -e "${RED}Errors occured on backup process!!!!${STD}"
     exit 2
 fi
-echo "Files saved"
-echo "Backup finished"
