[REF]

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,36 +1,36 @@
 #!/bin/bash
-if [ ! -f /etc/odoo/openerp-server.conf ]
-  then
-    echo "Error! odoo.conf not found!"
-    exit 2
-fi
+#if [ ! -f /etc/odoo/openerp-server.conf ]
+#  then
+#    echo "Error! odoo.conf not found!"
+#    exit 2
+#fi
 
-declare -A conf
+#declare -A conf
 
-IFS="="
-while read -r name value
-do
-  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
-  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
-  conf[$key]=$val
-done < /etc/odoo/openerp-server.conf
+#IFS="="
+#while read -r name value
+#do
+#  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
+#  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
+#  conf[$key]=$val
+#done < /etc/odoo/openerp-server.conf
 
-if [ ! -d /backup ]
-  then
-    mkdir /backup
-fi
+#if [ ! -d /backup ]
+#  then
+#    mkdir /backup
+#fi
+
 DATE=$(date +"%Y%m%d%H%M")
-
 DBFILE=/backup/${DBNAME}_${DATE}.dump
 TARFILE=/backup/${DBNAME}_${DATE}.tar
 
-PWD=${conf[db_password]}
-PWD="odoo"
-export PGPASSWORD=$PWD
-echo "Backup of database... pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} -f ${DBFILE} $DBNAME"
+#PWD=${conf[db_password]}
+#PWD="odoo"
+export PGPASSWORD="odoo"
+#echo "Backup of database... pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} -f ${DBFILE} $DBNAME"
 
 #pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} -f ${DBFILE} $DBNAME
-echo "Backup pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME"
+#echo "Backup pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME"
 pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME
 if [ $? -ne 0 ]
   then
