[REF]

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -1,19 +1,19 @@
 #!/bin/bash
-if [ ! -f /etc/odoo/openerp-server.conf ]
-  then
-    echo "Error! odoo.conf not found!"
-    exit 2
-fi
+#if [ ! -f /etc/odoo/openerp-server.conf ]
+#  then
+#    echo "Error! odoo.conf not found!"
+#    exit 2
+#fi
 
-declare -A conf
+#declare -A conf
 
-IFS="="
-while read -r name value
-do
-  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
-  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
-  conf[$key]=$val
-done < /etc/odoo/openerp-server.conf
+#IFS="="
+#while read -r name value
+#do
+#  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
+#  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
+#  conf[$key]=$val
+#done < /etc/odoo/openerp-server.conf
 
 if [ ! -d /backup ]
   then
@@ -45,14 +45,15 @@ if [ $? -ne 0 ]
 fi
 echo "Files restored"
 
-PWD=${conf[db_password]}
-export PGPASSWORD=$PWD
+#PWD=${conf[db_password]}
+export PGPASSWORD="odoo"
 echo "Drop database..."
-dropdb -U ${conf[db_user]} -h ${conf[db_host]} ${DBNAME}
+#dropdb -U ${conf[db_user]} -h ${conf[db_host]} ${DBNAME}
+dropdb -U odoo -h db ${DBNAME}
 
 echo "Restore of database..."
 #pg_restore -Fc -O -U ${conf[db_user]} -h ${conf[db_host]} -d ${DBNAME} ${DBFILE}
-pg_restore -U ${conf[db_user]} -h ${conf[db_host]} -d template1 -c -C ${DBFILE}
+pg_restore -U odoo -h db -d template1 -c -C ${DBFILE}
 
 if [ $? -ne 0 ]
   then
